all:                                                                                                                                                                                                        
        gcc ex2-16.c -o ex2-16.out
        gcc ex2-17.c -o ex2-17.out
        gcc ex2-18.c -o ex2-18.out
        gcc ex2-19.c -o ex2-19.out
        gcc ex2-20.c -o ex2-20.out
        gcc ex2-21.c -o ex2-21.out
        gcc ex2-23.c -o ex2-23.out
        gcc ex2-24.c -o ex2-24.out
        gcc ex2-25.c -o ex2-25.out
        gcc ex2-26.c -o ex2-26.out
        gcc ex2-27.c -o ex2-27.out
        gcc ex2-29.c -o ex2-29.out
        gcc ex2-30.c -o ex2-30.out
        gcc ex2-31.c -o ex2-31.out
        gcc ex2-32.c -o ex2-32.out

clean:
        @rm -f *.out
