all:                                                                                                                                                                                                        
        gcc ex3-16.c -o ex3-16.out
        gcc ex3-17.c -o ex3-17.out
        gcc ex3-18.c -o ex3-18.out
        gcc ex3-19.c -o ex3-19.out
        gcc ex3-20.c -o ex3-20.out
        gcc ex3-22.c -o ex3-22.out
        gcc ex3-23.c -o ex3-23.out
        gcc ex3-24.c -o ex3-24.out
        gcc ex3-25.c -o ex3-25.out
        gcc ex3-32.c -o ex3-32.out
        gcc ex3-33.c -o ex3-33.out 
        gcc ex3-34.c -o ex3-34.out 
        gcc ex3-35.c -o ex3-35.out 
        gcc ex3-36.c -o ex3-36.out -lm
        gcc ex3-37.c -o ex3-37.out 
        gcc ex3-38.c -o ex3-38.out
        gcc ex3-39.c -o ex3-39.out
        gcc ex3-41.c -o ex3-41.out
        gcc ex3-43.c -o ex3-43.out 
        gcc ex3-44.c -o ex3-44.out
        gcc ex3-45.c -o ex3-45.out
        gcc ex3-46.c -o ex3-46.out
        gcc ex3-47.c -o ex3-47.out
        gcc ex3-48.c -o ex3-48.out

clean:
        @rm -f *.out
