all:                                                                                                                                                                                                        
        gcc ex4-9.c -o ex4-9.out
        gcc ex4-10.c -o ex4-10.out
        gcc ex4-11.c -o ex4-11.out
        gcc ex4-12.c -o ex4-12.out
        gcc ex4-13.c -o ex4-13.out
        gcc ex4-14.c -o ex4-14.out
        gcc ex4-15.c -o ex4-15.out -lm
        gcc ex4-16.c -o ex4-16.out
        gcc ex4-17.c -o ex4-17.out
        gcc ex4-18.c -o ex4-18.out
        gcc ex4-19.c -o ex4-19.out
        gcc ex4-21.c -o ex4-21.out
        gcc ex4-22.c -o ex4-22.out
        gcc ex4-23.c -o ex4-23.out -lm
        gcc ex4-25.c -o ex4-25.out
        gcc ex4-26.c -o ex4-26.out
        gcc ex4-27.c -o ex4-27.out
        gcc ex4-28.c -o ex4-28.out
        gcc ex4-30.c -o ex4-30.out
        gcc ex4-31.c -o ex4-31.out
        gcc ex4-32.c -o ex4-32.out
        gcc ex4-33.c -o ex4-33.out
        gcc ex4-38.c -o ex4-38.out

clean:
        @rm -f *.out
